services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s

  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    read_only: true
    tmpfs:
      - /tmp
  test:
    build: .
    networks:
      - backend
    command: >
      sh -c "python manage.py test --no-input"
    volumes:
      - .:/app
    environment:
      TESTING: "true"

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge