# Generated by Django 5.1.7 on 2025-03-24 14:07

import django.db.models.deletion
from django.db import migrations, models

import dogs_api


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Tiny", "Tiny"),
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "freindliness",
                    dogs_api.models.Breed.RatingField(
                        help_text="Rating from 1 (low) to 5 (high)"
                    ),
                ),
                (
                    "trainability",
                    dogs_api.models.Breed.RatingField(
                        help_text="Rating from 1 (low) to 5 (high)"
                    ),
                ),
                (
                    "shedding_amount",
                    dogs_api.models.Breed.RatingField(
                        help_text="Rating from 1 (low) to 5 (high)"
                    ),
                ),
                (
                    "exercise_needs",
                    dogs_api.models.Breed.RatingField(
                        help_text="Rating from 1 (low) to 5 (high)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("favorite_food", models.CharField(max_length=100)),
                ("favorite_toy", models.CharField(max_length=100)),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dogs",
                        to="dogs_api.breed",
                    ),
                ),
            ],
        ),
    ]
